H12Auth2C/Controllers/AirportController.cs
using H12Auth2C.Data;
using H12Auth2C.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace H12Auth2C.Controllers
{
    [Authorize(Roles = UserRoles.Role_Admin)]
    public class AirportController : Controller
    {
        private readonly ApplicationDbContext o;
        public AirportController(ApplicationDbContext o)
        {
            this.o = o;
        }
        public IActionResult List()
        {
            var list = o.Airports.Include(x => x.City);
            return View(list.ToList());
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.CityName = new SelectList(o.Cities, "Id", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Add(Airport a)
        {
            if (ModelState.IsValid)
            {
                o.Airports.Add(a);
                o.SaveChanges();
                TempData["msjairport"] = "Havalimanı eklendi";
                return RedirectToAction("List");
            }
            ViewBag.CityName = new SelectList(o.Cities, "Id", "Name");
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                TempData["msjairport"] = "Lütfen bir havalimanı seçiniz";
                return RedirectToAction("List");
            }
            var flight = o.Airports.Include(x => x.Flights).Include(y => y.Flights1).FirstOrDefault(a => a.Id == id);

            if (flight is null)
            {
                TempData["msjairport"] = "Böyle bir havalimanı bulunamadi";
                return RedirectToAction("List");
            }
            if (flight.Flights.Count > 0)
            {
                TempData["msjairport"] = "Bu havalimanına ait biletler var önce biletleri siliniz";
                return RedirectToAction("List");
            }
            o.Airports.Remove(flight);
            o.SaveChanges();
            TempData["msjairport"] = "Havalimanı silindi";
            return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ViewBag.CityName = new SelectList(o.Cities, "Id", "Name");
            if (id == null)
            {
                TempData["msjairport"] = "Lütfen bir havalimanı seçiniz";
                return RedirectToAction("List");
            }
            var flight = o.Airports.Include(x => x.Flights).Include(y => y.Flights1).FirstOrDefault(a => a.Id == id);

            if (flight is null)
            {
                TempData["msjairport"] = "Böyle bir havalimanı bulunamadi";
                return RedirectToAction("List");
            }
            return View(flight);
        }
        [HttpPost]
        public IActionResult Edit(int? id, Airport a)
        {
            if (a.Id != id)
            {
                TempData["msjairport"] = "Böyle bir havalimanı bulunamadi";
                return RedirectToAction("List");
            }
            if (ModelState.IsValid)
            {
                o.Airports.Update(a);
                o.SaveChanges();
                TempData["msjairport"] = "Havalimanı güncellenmiştir";
                return RedirectToAction("List");
            }
            ViewBag.CityName = new SelectList(o.Cities, "Id", "Name");
            TempData["msjairport"] = "Havalimanı güncelleme işlemi başarısız";
            return View();
        }
    }
}

H12Auth2C/Controllers/CityController.cs
using H12Auth2C.Data;
using H12Auth2C.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace H12Auth2C.Controllers
{
    [Authorize(Roles = UserRoles.Role_Admin)]
    public class CityController : Controller
    {
        private readonly ApplicationDbContext o;
        public CityController(ApplicationDbContext o)
        {
            this.o = o;
        }
        public IActionResult List()
        {
            var list = o.Cities.Include(k => k.Country);
            return View(list.ToList());
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.CountryName = new SelectList(o.Countries, "Id", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Add(City c)
        {
            if (ModelState.IsValid)
            {
                o.Cities.Add(c);
                o.SaveChanges();
                TempData["msjcity"] = "Şehir başarılı bir şekilde eklenmiştir";
                return RedirectToAction("List");
            }
            ViewBag.CountryName = new SelectList(o.Countries, "Id", "Name");
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                TempData["msjcity"] = "Lütfen şehir seçiniz";
                return RedirectToAction("List");
            }
            var c = o.Cities.Include(x => x.Airports).FirstOrDefault(y => y.Id == id);
            if (c is null)
            {
                TempData["msjcity"] = "Böyle bir şehir bulunamadı";
                return RedirectToAction("List");
            }
            if (c.Airports.Count > 0)
            {
                TempData["msjcity"] = "Bu şehirin havalimanları var lütfen önce onları siliniz";
                return RedirectToAction("List");
            }
            o.Cities.Remove(c);
            o.SaveChanges();
            return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ViewBag.CountryName = new SelectList(o.Countries, "Id", "Name");
            if (id is null)
            {
                TempData["msjcity"] = "Lütfen bir şehir seçiniz";
                return RedirectToAction("List");
            }
            var c = o.Cities.FirstOrDefault(x => x.Id == id);
            if (c is null)
            {
                TempData["msjcity"] = "Böyle bir şehir bulunamadı";
                return RedirectToAction("List");
            }
            return View(c);
        }
        [HttpPost]
        public IActionResult Edit(int? id, City c)
        {
            if (id != c.Id)
            {
                TempData["msjcity"] = "Böyle bir şehir bulunamadi";
                return RedirectToAction("List");
            }
            if (ModelState.IsValid)
            {
                o.Cities.Update(c);
                o.SaveChanges();
                TempData["msjcity"] = "Seçilen şehir güncellenmiştir";
                return RedirectToAction("List");
            }
            ViewBag.CountryName = new SelectList(o.Countries, "Id", "Name");
            TempData["msjcity"] = "Hata !";
            return View();
        }
    }
}

H12Auth2C/Controllers/FlightController.cs
using H12Auth2C.Data;
using H12Auth2C.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace H12Auth2C.Controllers
{
    [Authorize(Roles = UserRoles.Role_Admin)]
    public class FlightController : Controller
    {
        private readonly ApplicationDbContext o;
        public FlightController(ApplicationDbContext o)
        {
            this.o = o;
        }
        public IActionResult List()
        {
            var list = o.Flights.
                Include(x => x.departurePlace).
                Include(y => y.arrivalPlace).
                Include(z => z.Plane.PlaneType);
            return View(list.ToList());
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.departurePlaceId = new SelectList(o.Airports, "Id", "AirportName");
            ViewBag.arrivalPlaceId = new SelectList(o.Airports, "Id", "AirportName");
            ViewBag.PlaneId = new SelectList(o.PlaneTypes, "Id", "modelName");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Flight f)
        {
            if (ModelState.IsValid)
            {
                if (f.departurePlaceId != f.arrivalPlaceId)
                {
                    o.Flights.Add(f);
                    o.SaveChanges();
                    TempData["msjf"] = "Uçuş eklendi";
                    return RedirectToAction("List");
                }
                TempData["msjf"] = "Kalkış yeri ile varış yeri aynı olamaz.";
                return RedirectToAction("List");
            }
            ViewBag.departurePlaceId = new SelectList(o.Airports, "Id", "AirportName");
            ViewBag.arrivalPlaceId = new SelectList(o.Airports, "Id", "AirportName");
            ViewBag.PlaneId = new SelectList(o.PlaneTypes, "Id", "modelName");
            return View();
        }
        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                TempData["msjf"] = "Lütfen bir uçuş seçiniz";
                return View();
            }
            var ticket = o.Flights.Include(x => x.Tickets).FirstOrDefault(y => y.Id == id);
            if (ticket is null)
            {
                TempData["msjf"] = "Böyle bir uçuş bulunamadi";
                return View();
            }
            if (ticket.Tickets.Count > 0)
            {
                TempData["msjf"] = "Bu uçuşa ait biletler var önce biletleri siliniz";
                return View();
            }
            o.Flights.Remove(ticket);
            o.SaveChanges();
            TempData["msjf"] = "Uçuş silindi";
            return RedirectToAction("List");
        }
        public IActionResult Edit(int? id)
        {
            ViewBag.departurePlaceId = new SelectList(o.Airports, "Id", "AirportName");
            ViewBag.arrivalPlaceId = new SelectList(o.Airports, "Id", "AirportName");
            ViewBag.PlaneId = new SelectList(o.PlaneTypes, "Id", "modelName");
            if (id == null)
            {
                TempData["msjf"] = "Lütfen bir uçuş seçiniz";
                return View();
            }
            var ticket = o.Flights.Include(x => x.Tickets).FirstOrDefault(y => y.Id == id);
            if (ticket is null)
            {
                TempData["msjf"] = "Böyle bir uçuş bulunamadi";
                return View();
            }
            return View(ticket);
        }
        [HttpPost]
        public IActionResult Edit(int? id, Flight f)
        {
            if (id != f.Id)
            {
                TempData["msjf"] = "Böyle bir uçuş yok";
                return View();
            }
            if (ModelState.IsValid)
            {
                o.Flights.Update(f);
                o.SaveChanges();
                TempData["msjf"] = "Uçuş düzenlendi";
                return RedirectToAction("List");
            }
            ViewBag.departurePlaceId = new SelectList(o.Airports, "Id", "AirportName");
            ViewBag.arrivalPlaceId = new SelectList(o.Airports, "Id", "AirportName");
            ViewBag.PlaneId = new SelectList(o.PlaneTypes, "Id", "modelName");
            TempData["msjf"] = "Uçuş güncelleme başarısız";
            return View();
        }
    }
}

H12Auth2C/Controllers/PlaneController.cs
using H12Auth2C.Data;
using H12Auth2C.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace H12Auth2C.Controllers
{
    [Authorize(Roles = UserRoles.Role_Admin)]
    public class PlaneController : Controller
    {
        private readonly ApplicationDbContext o;
        public PlaneController(ApplicationDbContext o)
        {
            this.o = o;
        }
        public IActionResult List()
        {
            var list = o.Planes.Include(k => k.PlaneType).Include(y => y.Company);
            return View(list.ToList());
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.CompanyName = new SelectList(o.Company, "Id", "Name");
            ViewBag.PlaneTypeName = new SelectList(o.PlaneTypes, "Id", "modelName");
            return View();
        }
        [HttpPost]
        public IActionResult Add(Plane c)
        {
            if (ModelState.IsValid)
            {
                o.Planes.Add(c);
                o.SaveChanges();
                TempData["msjplane"] = "Uçak başarılı bir şekilde eklenmiştir.";
                return RedirectToAction("List");
            }
            ViewBag.CompanyName = new SelectList(o.Company, "Id", "Name");
            ViewBag.PlaneTypeName = new SelectList(o.PlaneTypes, "Id", "modelName");
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                TempData["msjplane"] = "Lütfen uçak seçiniz";
                return RedirectToAction("List");
            }
            var c = o.Planes.Include(x => x.Flights).FirstOrDefault(y => y.Id == id);
            if (c is null)
            {
                TempData["msjplane"] = "Böyle bir uçak bulunamadı";
                return RedirectToAction("List");
            }
            if (c.Flights.Count > 0)
            {
                TempData["msjplane"] = "Bu uçağın uçuşu var lütfen önce uçuşu iptal ediniz";
                return RedirectToAction("List");
            }
            o.Planes.Remove(c);
            o.SaveChanges();
            return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ViewBag.CompanyName = new SelectList(o.Company, "Id", "Name");
            ViewBag.PlaneTypeName = new SelectList(o.PlaneTypes, "Id", "modelName");
            if (id is null)
            {
                TempData["msjplane"] = "Lütfen bir uçak seçiniz";
                return RedirectToAction("List");
            }
            var c = o.Planes.FirstOrDefault(x => x.Id == id);
            if (c is null)
            {
                TempData["msjplane"] = "Böyle bir uçak bulunamadı";
                return RedirectToAction("List");
            }
            return View(c);
        }
        [HttpPost]
        public IActionResult Edit(int? id, Plane c)
        {
            if (id != c.Id)
            {
                TempData["msjplane"] = "Böyle bir uçak bulunamadi";
                return RedirectToAction("List");
            }
            if (ModelState.IsValid)
            {
                o.Planes.Update(c);
                o.SaveChanges();
                TempData["msjplane"] = "Seçilen uçak güncellenmiştir";
                return RedirectToAction("List");
            }
            ViewBag.CompanyName = new SelectList(o.Company, "Id", "Name");
            ViewBag.PlaneTypeName = new SelectList(o.PlaneTypes, "Id", "modelName");
            TempData["msjplane"] = "Hata !";
            return View();
        }
    }
}

H12Auth2C/Views/Shared/_Layout.cshtml
@* <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - H12Auth2C</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/H12Auth2C.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Main" asp-action="Main">Ori Airlines</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin")){
                                   <li class="nav-item">
                                     <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="List">Fligt</a>
                                   </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Airport" asp-action="List">Airport</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="List">City</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="CallApiCompany" asp-action="Index">Company</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="List">Country</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Plane" asp-action="List">Plane</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="PlaneType" asp-action="List">PlaneType</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="MyTickets" asp-action="MyTickets">My tickets</a>
                                </li>
                            }
                            @if (User.IsInRole("Traveller"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="MyTickets" asp-action="MyTickets">My tickets</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - H12Auth2C - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
 *@
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - H12Auth2C</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/LayoutStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/H12Auth2C.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Main" asp-action="Main">Ori Airlines</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                        Admin Operations
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarDarkDropdownMenuLink">
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Flight" asp-action="List">Flights </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Airport" asp-action="List">Airports </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="List">Cities</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="CallApiCompany" asp-action="Index">Company</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="List">Countries</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Plane" asp-action="List">Plane</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="PlaneType" asp-action="List">Plane Types</a>
                                        </li>
                                    </ul>
                                </li>
                            }
                            @if (User.IsInRole("Traveller") || User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="MyTickets" asp-action="MyTickets">My tickets</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>